/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitydb;

/**
 *
 * @author Joydeep
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Classroom = new javax.swing.JRadioButton();
        Department = new javax.swing.JRadioButton();
        Course = new javax.swing.JRadioButton();
        Exit = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Instructor = new javax.swing.JRadioButton();
        Section = new javax.swing.JRadioButton();
        Student = new javax.swing.JRadioButton();
        Takes = new javax.swing.JRadioButton();
        Advisor = new javax.swing.JRadioButton();
        TimeSlot = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MAIN MENU");

        Classroom.setText("Classroom");

        Department.setText("Department");

        Course.setText("Course");

        Exit.setText("Exit");

        jButton1.setText("Next>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Instructor.setText("Instructor");

        Section.setText("Section");

        Student.setText("Student");

        Takes.setText("Takes");

        Advisor.setText("Advisor");

        TimeSlot.setText("Time Slot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Classroom)
                            .addComponent(Department)
                            .addComponent(Course)
                            .addComponent(Exit))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Takes)
                            .addComponent(Student)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Instructor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Section))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TimeSlot)
                                    .addComponent(Advisor)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Classroom)
                    .addComponent(Instructor)
                    .addComponent(Advisor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department)
                    .addComponent(Section)
                    .addComponent(TimeSlot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Course)
                    .addComponent(Student))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(Takes))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Classroom.isSelected())
        {
            ClassroomForm cf = new ClassroomForm();
            cf.setVisible(true);
            String m[] = {};
            cf.main(m);
            cf.isEnabled();
            this.setVisible(false);
        }
        else if(Department.isSelected())
        {
            DepartmentForm df = new DepartmentForm ();
            df.setVisible(true);
            String m[] = {};
            df.main(m);
            df.isEnabled();
            this.setVisible(false);
        }
        else if(Course.isSelected())
        {
            CourseForm cf = new CourseForm();
            cf.setVisible(true);
            String m[] = {};
            cf.main(m);
            cf.isEnabled();
            this.setVisible(false);
        }
        else if(Instructor.isSelected())
        {
            InstructorForm i = new InstructorForm ();
            i.setVisible(true);
            String m[] = {};
            i.main(m);
            i.isEnabled();
            this.setVisible(false);
        }
        else if(Section.isSelected())
        {
            SectionForm sf = new SectionForm ();
            sf.setVisible(true);
            String m[] = {};
            sf.main(m);
            sf.isEnabled();
            this.setVisible(false);
        }
        else if(Student.isSelected())
        {
            StudentForm sf = new StudentForm ();
            sf.setVisible(true);
            String m[] = {};
            sf.main(m);
            sf.isEnabled();
            this.setVisible(false);
        }
        else if(Takes.isSelected())
        {
            TakesForm tf = new TakesForm ();
            tf.setVisible(true);
            String m[] = {};
            tf.main(m);
            tf.isEnabled();
            this.setVisible(false);
        }
        if(Advisor.isSelected())
        {
            AdvisorForm af = new AdvisorForm();
            String m[] = {};
            AdvisorForm.main(m);
            af.isEnabled();
            this.setVisible(false);
        }
        else if(TimeSlot.isSelected())
        {
            TimeSlotForm tsf = new TimeSlotForm ();
            tsf.setVisible(true);
            String m[] = {};
            tsf.main(m);
            tsf.isEnabled();
            this.setVisible(false);
        }
        else if(Exit.isSelected())
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Advisor;
    private javax.swing.JRadioButton Classroom;
    private javax.swing.JRadioButton Course;
    private javax.swing.JRadioButton Department;
    private javax.swing.JRadioButton Exit;
    private javax.swing.JRadioButton Instructor;
    private javax.swing.JRadioButton Section;
    private javax.swing.JRadioButton Student;
    private javax.swing.JRadioButton Takes;
    private javax.swing.JRadioButton TimeSlot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
